### ISSUE TITLE
Why does nothing change after running it?

### ISSUE THREAD

**Issue by NeilWang079** [TemryL/ComfyUI-IDM-VTON#10]
![2024-05-04 001722](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/42379975/2a0ca94f-a871-406c-b2e0-95cb5ebabf15)
![024-05-04 001835](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/42379975/911fcfc8-0bc0-45ee-bb65-23bfe2fa140b)

**Comment by TemryL** [comment]
hey, regarding your terminal screenshot, it looks like the pipeline is performing only 15 denoising steps. Have you changed the `num_inference_steps` parameter? If yes, try to increase it to 30. 

Also, can you tell me your GPU config and provide the json version of the workflow you ran?

**Comment by TemryL** [comment]
@NeilWang079 were you able to resolve your issue?
