### ISSUE TITLE
The color doesn't match after changing into clothes

### ISSUE THREAD

**Issue by xiaoboelse** [TemryL/ComfyUI-IDM-VTON#13]
Thank you for the author's efforts, but the testing was slow and the size did not match well. It must be a multiple of 8, and the most crucial thing is that the color did not match after changing into clothes
![微信截图_20240504115339](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/121392142/77c58d02-4607-4a64-a65c-ba727c507ec4)

**Comment by taoisu** [comment]
Confirming the same issue. On the other hand, this demo page is giving the right result: https://huggingface.co/spaces/yisol/IDM-VTON

Is there a bug?

**Comment by whitepapercg** [comment]
> Hi guys, yes it is a bug that needs to be fixed! I think it comes from the mask generation with SAM because in the demo the mask is much bigger and does not cover only the clothe but the whole upper body. One idea could be to try to load a manually generated mask and see what happens. If their is still a mismatch color, then probably the preprocessing of the images in the inference pipeline is wrong. Let me know if you can investigate on that. Thanks!

I tried using different masks, it didn't help

**Comment by TemryL** [comment]
I just updated the input preprocessing which should give more consistent results.

Feel free to try again with your inputs and share your outputs here?

Cheers!

**Comment by 01-111162-173** [comment]
it has the same question now, the color is not match the garment color, for ex. the garment color is black, generate  image is gray
