### ISSUE TITLE
Clothing articles inconsistent.. Is this an error on my end or a bug to be fixed?

### ISSUE THREAD

**Issue by HydraBucket** [TemryL/ComfyUI-IDM-VTON#17]
From the examples I've ran, it seems although the masking and clothing creation is phenomenal. It isn't properly creating the fabrics, colours, and length of referenced. Thank you for your continued work, this node has promise to be amazing. Reference image (drawings included)

<img width="1588" alt="image" src="https://github.com/TemryL/ComfyUI-IDM-VTON/assets/154306621/0bc8b223-572d-4358-910b-3523a24b5080">

**Comment by HydraBucket** [comment]
It seems as if shifting the model input prompt changes the final output. Is this meant to be?

<img width="1661" alt="image" src="https://github.com/TemryL/ComfyUI-IDM-VTON/assets/154306621/fdde9b30-e673-42c6-874e-20a42b11b49a">

**Comment by TemryL** [comment]
Thanks for your great insights! 

The `model_prompt` input is actually misleading as it should always be something like `f"the model is wearing {garment_description}"`. Therefore I removed this input.
 
I also updated the input preprocessing which should give more consistent results. 

Could you please try again with your inputs and share your outputs here?

Thanks!

**Comment by HydraBucket** [comment]
Hey Temryl, 

Thanks for getting back to me! Unfortunately, it doesnt seem as if the prompts have changed the outcome. Before generation, I hit update all through Comfy manager. I assume this would implement the changes you've created.

<img width="1892" alt="image" src="https://github.com/TemryL/ComfyUI-IDM-VTON/assets/154306621/7793e05e-b12c-4b8b-8746-a59de4ed0bb6">

**Comment by TemryL** [comment]
I think you should update, restart, clear the workspace and import the new workflow

**Comment by ParticleDog** [comment]
In this case you should mask the image manually to cover the whole body of original person
