### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by anyavicmac** [TemryL/ComfyUI-IDM-VTON#20]
Hey in the workflow the node is red when installing the node - and I'm getting ímport failed'- please help!!

**Comment by anyavicmac** [comment]
this is what it looks like in comfyui; 
![image](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/169254185/82980c6b-fbcf-4cb3-a8f0-dbc80545cc1e)

**Comment by TemryL** [comment]
have you tried to update?

**Comment by anyavicmac** [comment]
Hey still same issuee after downloading manually.. 
![image](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/169254185/94ba5f06-8ac1-4571-9279-4804d442eb89) and got another issue first whilst booting comfyui could be connected to this cause i wasnt getting this error before; 
![image](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/169254185/c5f06b80-4647-4146-b65a-feb944a4b3e7)

**Comment by anyavicmac** [comment]
![image](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/169254185/e8b02f59-21e7-4a53-969c-4dd530fb6732)
also here

**Comment by DennLie** [comment]
I am facing the same problem.

**Comment by anyavicmac** [comment]
same! I updated it after installing manually and it worked! thanks guys
