### ISSUE TITLE
Transfer of weights to ComfyUI/models

### ISSUE THREAD

**Issue by whitepapercg** [TemryL/ComfyUI-IDM-VTON#31]
Hi, I think it would be wise to move the download of the weights from the default Huggingface path to the models folder in ComfyUI

**Comment by TemryL** [comment]
Yes, it would be much better! (https://github.com/TemryL/ComfyUI-IDM-VTON/issues/2) 
I will probably solve this https://github.com/TemryL/ComfyUI-IDM-VTON/issues/28 at the same time.
