### ISSUE TITLE
Error occurred when executing PipelineLoader

### ISSUE THREAD

**Issue by HDKKZn** [TemryL/ComfyUI-IDM-VTON#36]
float16 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.

I just drag workflow.png into the comfyui, after downloading the models, an error was reported. I am already used command huggingface-cli login, but it does not work
![image](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/58685634/8657c407-4570-4fa7-ae5a-c32769af3658)

**Comment by TemryL** [comment]
Thanks for your report. The workflow needs to be updated. In the meantime, you can specify the correct path to the weights in `ckpt_path` argument of the pipeline loader node.
