### ISSUE TITLE
Load IDM-VTON Pipeline - float16 Issue

### ISSUE THREAD

**Issue by martinupwork20** [TemryL/ComfyUI-IDM-VTON#41]
Everything seem working fine, but got stuck in “Load IDM-VTON Pipeline - float16” ?

OSError: float16 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.
<img width="1324" alt="Screenshot 2024-05-24 at 6 37 50 PM" src="https://github.com/TemryL/ComfyUI-IDM-VTON/assets/67407491/b0abd691-a9b0-425e-aea5-277e4d2b872e">
<img width="1350" alt="Screenshot 2024-05-24 at 6 39 32 PM" src="https://github.com/TemryL/ComfyUI-IDM-VTON/assets/67407491/408708e0-9ec8-4fd5-b4a4-0127878ff522">

**Comment by TemryL** [comment]
The pipeline loader node, has been updated. You now need to download the weights and specify ´ckpt_path´. See readme

**Comment by UrielTac** [comment]
![Captura de pantalla 2024-05-25 043716](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/165091096/44c4a090-56c8-458b-bb74-64756152fc26)
Please help, download the models and specify 'ckpt path'

**Comment by martinupwork20** [comment]
> The pipeline loader node, has been updated. You now need to download the weights and specify ´ckpt_path´. See readme

Thank you for your rapid response, yes indeed, before I raise this issue I have already downloaded all the necessary weights and save it in a folder: /ComfyUI/custom_nodes/ComfyUI-IDM-VTON/models. But I'm not quite sure how to specify the´ckpt_path´ ? which .py file I need to specify in? BTW I am using Mac M2 machine, that may not be compatible?

<img width="770" alt="Screenshot 2024-05-26 at 11 26 24 PM" src="https://github.com/TemryL/ComfyUI-IDM-VTON/assets/67407491/b4fa067a-6a82-4920-8b43-7525e532f812">

**Comment by TemryL** [comment]
In your case, you should specify `/custom_nodes/ComfyUI-IDM-VTON/models/idm_vton`. LMK if that works.

**Comment by martinupwork20** [comment]
May I ask how to specify? as in where? on the workflow UI? ..... do apologise if I have asked a silly question XD

**Comment by martinupwork20** [comment]
> In your case, you should specify `/custom_nodes/ComfyUI-IDM-VTON/models/idm_vton`. LMK if that works.

May I ask how to specify? as in where? on the workflow UI? ..... do apologise if I have asked a silly question ha..haa..
From where? which file? src/idm_vton/ >>>>> "tryon_pipeline.py"?
I guessed I should set something like this? right? THX.

import os

# Set the path to your model weights
ckpt_path = "/Volumes/2T/Martin/MacStudio/ChangeClothes/ComfyUI/custom_nodes/ComfyUI-IDM-VTON/models/idm_vton"

# Example function to load model weights
def load_model_weights():
    # Load the model weights from the specified path
    model = SomeModelClass()
    model.load_weights(os.path.join(ckpt_path, 'model_weights_file.h5'))

load_model_weights()

**Comment by martinupwork20** [comment]
> In your case, you should specify `/custom_nodes/ComfyUI-IDM-VTON/models/idm_vton`. LMK if that works.

got prompt
Failed to validate prompt for output 20:
* IDM-VTON 19:
  - Required input is missing: human_img
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error: 
	(null)
	Internal Error (0000000e:Internal Error)
	<AGXG14XFamilyCommandBuffer: 0x5a1ecc930>
    label = <none> 
    device = <AGXG14CDevice: 0x10ede7000>
        name = Apple M2 Max 
    commandQueue = <AGXG14XFamilyCommandQueue: 0x10ee5e200>
        label = <none> 
        device = <AGXG14CDevice: 0x10ede7000>
            name = Apple M2 Max 
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error: 
	(null)
	Internal Error (0000000e:Internal Error)
	<AGXG14XFamilyCommandBuffer: 0x31d70e630>
    label = <none> 
    device = <AGXG14CDevice: 0x10ede7000>
        name = Apple M2 Max 
    commandQueue = <AGXG14XFamilyCommandQueue: 0x10ee5e200>
        label = <none> 
        device = <AGXG14CDevice: 0x10ede7000>
            name = Apple M2 Max 
    retainedReferences = 1
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error: 
	(null)
	Internal Error (0000000e:Internal Error)
	<AGXG14XFamilyCommandBuffer: 0x31d70e630>
    label = <none> 
    device = <AGXG14CDevice: 0x10ede7000>
        name = Apple M2 Max 
    commandQueue = <AGXG14XFamilyCommandQueue: 0x10ee5e200>
        label = <none> 
        device = <AGXG14CDevice: 0x10ede7000>
            name = Apple M2 Max 
    retainedReferences = 1
Prompt executed in 46.75 seconds

**Comment by TemryL** [comment]
Hi, I just updated the downloading weights and `workflow.png`. LMK

**Comment by martinupwork20** [comment]
> Hi, I just updated the downloading weights and `workflow.png`. LMK

Yeap!, working perfectly fine now, Many Thanks +3000

**Comment by TemryL** [comment]
Nice!
