### ISSUE TITLE
Feature Request: Auto-Masking Node

### ISSUE THREAD

**Issue by spenpal** [TemryL/ComfyUI-IDM-VTON#53]
Is it possible to add a node for auto-masking (just like the [one](https://huggingface.co/spaces/yisol/IDM-VTON) on the HF Hub demo)?

**Comment by TemryL** [comment]
Can you give more details? The current implementation already auto generate mask using SAM.

**Comment by spenpal** [comment]
From what I see on the documentation, you have give a prompt to SAM for it to generate a mask of the clothing.

On the IDM VTON Hugging Face demo, there is an option for "Generate Auto-Mask", which doesn't ask for any input. It automatically masks the upper body portion of your human.

Correct me if I am wrong, but I don't see any option in the IDM VTON nodes to do the same functionality.

**Comment by TemryL** [comment]
Yes, you're right! However, I think the mask generation is out of IDM-VTON scope as there are many ways to generate masks and SAM is just one of them. From what I saw, the demo uses OpenPose detector as annotator and this seems to be already implemented in [ControlNet](https://github.com/lllyasviel/ControlNet) nodes.

**Comment by spenpal** [comment]
Thanks for letting me know! I will check out the ControlNet nodes then.

**Comment by TemryL** [comment]
Let me know if you find what you are looking for! If yes, we could add it as a workflow example.
