### ISSUE TITLE
"LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by ParticleDog** [TemryL/ComfyUI-IDM-VTON#6]
After pulling the latest  commit, error ocurred:

"LayerNormKernelImpl" not implemented for 'Half'

**Comment by TemryL** [comment]
are you running with mps accelerator?

**Comment by ParticleDog** [comment]
> are you running with mps accelerator?

I am not sure what mps accelerator is ... Is it a kind of cpu accelerator for pytorch?

**Comment by ParticleDog** [comment]
I changed the code in pipeline_loader.py from "weight_dtype = torch.float16" to "weight_dtype = torch.float32", it seems that the error was bypassed. 
But another error occured,  which also appeared before I pulled the latest commit:

!!! Exception during processing!!! Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 1024, 1024, 768] to have 3 channels, but got 1024 channels instead

**Comment by TemryL** [comment]
yes, running on cpu needs float32 but float16 works on gpu. 
Concerning the last error you mentioned, it will be fixed very soon in the next commit
Thanks for your precious feedbacks!!

**Comment by TemryL** [comment]
@ParticleDog dimension issue should be fix now
