### ISSUE TITLE
Error occurred when executing PipelineLoader

### ISSUE THREAD

**Issue by tjie82921** [TemryL/ComfyUI-IDM-VTON#71]
Error occurred when executing PipelineLoader:

Error no file named config.json found in directory E:\ComfyUI_windows_portable\ComfyUI\models\IDM-VTON.

![20240816144043](https://github.com/user-attachments/assets/057a7613-eaae-4122-8735-719e2c78afe7)

Where can I find "config.json"? Earlier, I used this project and was amazed by the results. However, when I used it again recently, it showed in comfyUI that it could be upgraded, but after the upgrade, the entire process was no longer usable. I tried to reinstall it and it still did not change. The error message was that "config.json" could not be found. Do some files need to be renamed after downloading? Or did I not find the download address for this "config.json"?

**Comment by TemryL** [comment]
Hey, have you tried to manually run install.py?

**Comment by tjie82921** [comment]
No, I didn't, because I'm not familiar with programming, so when I read this instruction,
![20240817004013](https://github.com/user-attachments/assets/5f461acf-6e0c-49cd-802e-05c697933e34)
 I didn't fully understand what it meant. Could you please explain what it means and guide me on how to use this node correctly?

**Comment by tjie82921** [comment]
> 嘿，您尝试过手动运行 install.py 吗？

After I run python install.py, the following code appears, prompting me that folder_paths is missing. Please teach me how to deal with it next.
![微信截图_20240818044528](https://github.com/user-attachments/assets/435b843c-e271-4a37-8fac-da4bc0d5b7b7)

**Comment by TemryL** [comment]
Hi, I think `install.py` should be run from the root of ComfyUI. Can you try moving to the root dir and run something like:

```bash
python custom_nodes/ComfyUI-IDM-VTON/install.py
```

Let me know if that works.

**Comment by TemryL** [comment]
duplicates of https://github.com/TemryL/ComfyUI-IDM-VTON/issues/72

**Comment by tjie82921** [comment]
> Hi, I think `install.py` should be run from the root of ComfyUI. Can you try moving to the root dir and run something like:你好，我认为`install.py`应该从 ComfyUI 的根目录运行。您可以尝试移动到根目录并运行以下命令：
> 
> ```shell
> python custom_nodes/ComfyUI-IDM-VTON/install.py
> ```
> 
> Let me know if that works.让我知道这是否有效。

it great,Thanks for your reply, I can use it now
