### ISSUE TITLE
ModuleNotFoundError: No module named 'folder_paths'

### ISSUE THREAD

**Issue by suanow** [TemryL/ComfyUI-IDM-VTON#72]
Hi! I try to run the flow on google cloud vm, but when running python install.py i face this issue:

comfyvm:~/ComfyUI/custom_nodes/ComfyUI-IDM-VTON$ python install.py
Traceback (most recent call last):
  File "/home/suanow/ComfyUI/custom_nodes/ComfyUI-IDM-VTON/install.py", line 6, in <module>
    from folder_paths import models_dir
ModuleNotFoundError: No module named 'folder_paths'

Any ideas on how to fix it? all other things ive tried to run (not connected to IDM-VTON) does not have this issue. Thanks in advance

**Comment by TemryL** [comment]
Hi, I think `install.py` should be run from the root of ComfyUI. Can you try moving to the root dir and run something like:

```bash
python custom_nodes/ComfyUI-IDM-VTON/install.py
```

Let me know if that works.

**Comment by suanow** [comment]
if i understand you properly, i've cd'ed to ComfyUI dir and run the command. However, the issue is still the same

Command from term: ~/ComfyUI$ python custom_nodes/ComfyUI-IDM-VTON/install.py
Error: Traceback (most recent call last):
  File "/home/suanow/ComfyUI/custom_nodes/ComfyUI-IDM-VTON/install.py", line 6, in <module>
    from folder_paths import models_dir
ModuleNotFoundError: No module named 'folder_paths'

**Comment by TemryL** [comment]
Hey @WAS-PlaiLabs, I think your last PR broke the install. Could you tell us how `install.py`should be run (as it import folder_paths from comfyui) and maybe update the readme if you have some times? Thanks!

**Comment by WASasquatch** [comment]
The install will probably need add ComfyUI base to sys paths in order to import it's folder management module.

**Comment by WASasquatch** [comment]
Yeah I believe all that's needed is to add to sys path, just backup two directories since we don't know users system: `sys.path.append('../../')` added before the import https://github.com/TemryL/ComfyUI-IDM-VTON/blob/main/install.py#L5

I can make a PR when I am home if need be but should be simple fix. I actually assumed this install was ran within ComfyUI -- in fact you may think about doing that. Use the `startup_script.py` file which runs before ComfyUI starts. If using Manager you wouldn't have to worry about installing requirements, just downloading weights to the folder.

**Comment by suanow** [comment]
TY, wil try to fix this. I was having the same issue with manager some time before, but was fixing it with deleting and redownloading the node in "missing node". However, now the manager does not allow me to fix it somehow.

thanks once again for helping!

**Comment by Y-ujl** [comment]
You can modify the install.py file to comment out folder_paths and change them to the absolute paths of models/IDM-VTON
# from folder_paths import models_dir
models_dir= "/opt/xx/ComfyUI/models/"

**Comment by WAS-PlaiLabs** [comment]
https://github.com/TemryL/ComfyUI-IDM-VTON/pull/73

**Comment by lkylove** [comment]
import sys
import os
import subprocess
from huggingface_hub import snapshot_download

sys.path.append("../../")
'# from folder_paths import models_dir

CUSTOM_NODES_PATH = os.path.dirname(os.path.abspath(__file__))
'# WEIGHTS_PATH = os.path.join(models_dir, "IDM-VTON")
WEIGHTS_PATH = "C:\DEV\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\models\/IDM-VTON"
HF_REPO_ID = "yisol/IDM-VTON"
