### ISSUE TITLE
Installing from ComfyUI Manager or via Github link doesn't work

### ISSUE THREAD

**Issue by xulander** [TemryL/ComfyUI-IDM-VTON#80]
I've installed, uninstalled multiple times through the ComfyUI Manager as well as through the Github link, but it seems none of the files, weights, configs etc are downloaded. 

When going into ComfyUI/models/IDM-VTON, the folder is completely empty. I've tried pulling in the scheduler_config manually, but then there are just more missing files.

This is the error:
Error occurred when executing PipelineLoader:

Error no file named scheduler_config.json found in directory /home/ubuntu/ComfyUI/models/IDM-VTON.

**Comment by xulander** [comment]
Looking at the logs, this might seem relevant 

[!] WARNING: Error parsing requirements for pip: [Errno 2] No such file or directory: '/opt/tensorflow/lib/python3.10/site-packages/pip-23.0.1.dist-info/METADATA'
[!] WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
[!] Traceback (most recent call last):
[!]   File "/home/ubuntu/user_data/comfyui/custom_nodes/ComfyUI-IDM-VTON/install.py", line 7, in <module>
[!]     from folder_paths import models_dir
[!] ModuleNotFoundError: No module named 'folder_paths'

**Comment by xulander** [comment]
Oddly enough, it seems that after trying to download from git again rather than the comfy manager finally worked..

**Comment by TemryL** [comment]
Hi, I guess your issue was related to https://github.com/TemryL/ComfyUI-IDM-VTON/issues/72. Pretty weird that you got this issue after installing from comfyui manager though

**Comment by liangzhukun** [comment]
I also encountered the same problem, but I don't know how to download the model or which one to download
