### ISSUE TITLE
(IMPORT FAILED) when installing IDM-VTON with the Confyui manager

### ISSUE THREAD

**Issue by Alexander-RPR** [TemryL/ComfyUI-IDM-VTON#86]
Hello, I have a problem (IMPORT FAILED) when installing IDM-VTON with the Confyui manager

Here I leave the code trace when running my ConfyUI:

D:\Comfy\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-13 09:39:47.143600
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\Comfy\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\Comfy\ComfyUI_windows_portable\ComfyUI
** Log path: D:\Comfy\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   8.2 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12287 MB, total RAM 16253 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\Comfy\ComfyUI_windows_portable\ComfyUI\web
D:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Adding D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V7.11.3)
Loaded ImpactPack nodes from D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: AMD Ryzen 7 5700G with Radeon Graphics - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3060
[Crystools INFO] NVIDIA Driver: 565.90
Traceback (most recent call last):
  File "D:\Comfy\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\__init__.py", line 2, in <module>
    from .src.nodes_mappings import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\nodes_mappings.py", line 1, in <module>
    from .nodes.pipeline_loader import PipelineLoader
  File "D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON\src\nodes\pipeline_loader.py", line 6, in <module>
    from diffusers import AutoencoderKL, DDPMScheduler
  File "D:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "D:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "D:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (D:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?

Cannot import D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (D:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)
### Loading: ComfyUI-Impact-Pack (V7.11.3)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.6)
Total VRAM 12287 MB, total RAM 16253 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
### ComfyUI Revision: 2827 [8ebf2d88] *DETACHED | Released on '2024-11-12'
OpenPose Editor: Loaded
D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-segment-anything-2\sam2\modeling\sam\transformer.py:20: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
Imported node: DT_Play_Sound_At_Execution
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
D:\Comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()

[rgthree-comfy] Loaded 42 magnificent nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "The only way to do great work is to love what you do." - Steve Jobs

Import times for custom nodes:
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_face_parsing
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.2 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels
   0.3 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.3 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.3 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
   0.4 seconds (IMPORT FAILED): D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON
   0.5 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.6 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   2.2 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   2.3 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
   2.7 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   4.3 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   4.4 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
  12.5 seconds: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
Traceback (most recent call last):
  File "D:\Comfy\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\Comfy\ComfyUI_windows_portable\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 150, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1056, in iterdir
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'D:\\Comfy\\ComfyUI_windows_portable\\ComfyUI\\models\\LLM'

FETCH DATA from: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: D:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]

**Comment by Alexander-RPR** [comment]
Hi, I was able to resolve this error.
You just need to uninstall the huggingface_hub you have and install huggingface_hub 0.25.0 in the python_embeded folder of Confyui portable

In the folder open CMD
python.exe -m pip uninstall huggingface_hub
- yes

Now install version 0.25.0
python.exe -m pip install huggingface_hub==0.25.0

And done, open again the Confyui

**Comment by smartinkcherian** [comment]
@Alexander-RPR  Thanks, it worked for me
